name: IndustrialConfigurator
options:
  bundleIdPrefix: com.industrial
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

targets:
  IndustrialConfigurator:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - IndustrialConfigurator
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.industrial.IndustrialConfigurator
        INFOPLIST_FILE: IndustrialConfigurator/Info.plist
        SWIFT_VERSION: "5.9"
        ENABLE_PREVIEWS: YES
    scheme:
      testTargets:
        - IndustrialConfiguratorTests
    info:
      path: IndustrialConfigurator/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleDisplayName: Industrial Configurator
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"

  IndustrialConfiguratorTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - IndustrialConfiguratorTests
    dependencies:
      - target: IndustrialConfigurator
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.industrial.IndustrialConfiguratorTests
        SWIFT_VERSION: "5.9"

schemes:
  IndustrialConfigurator:
    build:
      targets:
        IndustrialConfigurator: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - IndustrialConfiguratorTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
